# Generated by Django 3.0.5 on 2020-05-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]

# BEGIN;
# --
# -- Create model Choice
# --
# CREATE TABLE "polls_choice" (
#     "id" serial NOT NULL PRIMARY KEY,
#     "choice_text" varchar(200) NOT NULL,
#     "votes" integer NOT NULL
# );
# --
# -- Create model Question
# --
# CREATE TABLE "polls_question" (
#     "id" serial NOT NULL PRIMARY KEY,
#     "question_text" varchar(200) NOT NULL,
#     "pub_date" timestamp with time zone NOT NULL
# );
# --
# -- Add field question to choice
# --
# ALTER TABLE "polls_choice" ADD COLUMN "question_id" integer NOT NULL;
# ALTER TABLE "polls_choice" ALTER COLUMN "question_id" DROP DEFAULT;
# CREATE INDEX "polls_choice_7aa0f6ee" ON "polls_choice" ("question_id");
# ALTER TABLE "polls_choice"
#   ADD CONSTRAINT "polls_choice_question_id_246c99a640fbbd72_fk_polls_question_id"
#     FOREIGN KEY ("question_id")
#     REFERENCES "polls_question" ("id")
#     DEFERRABLE INITIALLY DEFERRED;

# COMMIT;